[2025-01-07T01:41:55.636+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-07T01:41:55.652+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ico_scraping_dag_entire_v02.scrape_ico_data manual__2025-01-07T01:36:50.764658+00:00 [queued]>
[2025-01-07T01:41:55.660+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ico_scraping_dag_entire_v02.scrape_ico_data manual__2025-01-07T01:36:50.764658+00:00 [queued]>
[2025-01-07T01:41:55.660+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-07T01:41:55.676+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_ico_data> on 2025-01-07 01:36:50.764658+00:00
[2025-01-07T01:41:55.686+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ico_scraping_dag_entire_v02', 'scrape_ico_data', 'manual__2025-01-07T01:36:50.764658+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/selenium_dag_01.py', '--cfg-path', '/tmp/tmp9iidl2hk']
[2025-01-07T01:41:55.690+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask scrape_ico_data
[2025-01-07T01:41:55.691+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3088) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-07T01:41:55.691+0000] {standard_task_runner.py:72} INFO - Started process 3090 to run task
[2025-01-07T01:41:55.741+0000] {task_command.py:467} INFO - Running <TaskInstance: ico_scraping_dag_entire_v02.scrape_ico_data manual__2025-01-07T01:36:50.764658+00:00 [running]> on host e0f05d443e24
[2025-01-07T01:41:55.825+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ico_scraping_dag_entire_v02' AIRFLOW_CTX_TASK_ID='scrape_ico_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T01:36:50.764658+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T01:36:50.764658+00:00'
[2025-01-07T01:41:55.827+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-07T01:41:55.842+0000] {logging_mixin.py:190} INFO - Starting the web scraping process...
[2025-01-07T01:41:55.888+0000] {logging_mixin.py:190} INFO - Chrome version: Chromium 114.0.5735.0
[2025-01-07T01:41:55.888+0000] {logging_mixin.py:190} INFO - ChromeDriver version: ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})
[2025-01-07T01:41:55.889+0000] {logging_mixin.py:190} INFO - Chrome binary location set to: /opt/chrome/chrome
[2025-01-07T01:41:55.890+0000] {logging_mixin.py:190} INFO - ChromeDriver path set to: /opt/chromedriver/chromedriver
[2025-01-07T01:41:56.005+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 153, in scrape_data
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x562c4721a4e3 <unknown>
#1 0x562c46f49c76 <unknown>
#2 0x562c46f30ce2 <unknown>
#3 0x562c46f32162 <unknown>
#4 0x562c46f320b4 <unknown>
#5 0x562c46f2258e <unknown>
#6 0x562c46f22245 <unknown>
#7 0x562c46fade2c <unknown>
#8 0x562c46fad47f <unknown>
#9 0x562c46fa4de3 <unknown>
#10 0x562c46f7a2dd <unknown>
#11 0x562c46f7b34e <unknown>
#12 0x562c471da3e4 <unknown>
#13 0x562c471de3d7 <unknown>
#14 0x562c471e8b20 <unknown>
#15 0x562c471df023 <unknown>
#16 0x562c471ad1aa <unknown>
#17 0x562c472036b8 <unknown>
#18 0x562c47203847 <unknown>
#19 0x562c47213243 <unknown>
#20 0x7f49b19111c4 <unknown>

[2025-01-07T01:41:56.017+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ico_scraping_dag_entire_v02, task_id=scrape_ico_data, run_id=manual__2025-01-07T01:36:50.764658+00:00, execution_date=20250107T013650, start_date=20250107T014155, end_date=20250107T014156
[2025-01-07T01:41:56.029+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-07T01:41:56.029+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task scrape_ico_data (Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x562c4721a4e3 <unknown>
#1 0x562c46f49c76 <unknown>
#2 0x562c46f30ce2 <unknown>
#3 0x562c46f32162 <unknown>
#4 0x562c46f320b4 <unknown>
#5 0x562c46f2258e <unknown>
#6 0x562c46f22245 <unknown>
#7 0x562c46fade2c <unknown>
#8 0x562c46fad47f <unknown>
#9 0x562c46fa4de3 <unknown>
#10 0x562c46f7a2dd <unknown>
#11 0x562c46f7b34e <unknown>
#12 0x562c471da3e4 <unknown>
#13 0x562c471de3d7 <unknown>
#14 0x562c471e8b20 <unknown>
#15 0x562c471df023 <unknown>
#16 0x562c471ad1aa <unknown>
#17 0x562c472036b8 <unknown>
#18 0x562c47203847 <unknown>
#19 0x562c47213243 <unknown>
#20 0x7f49b19111c4 <unknown>
; 3090)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 153, in scrape_data
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x562c4721a4e3 <unknown>
#1 0x562c46f49c76 <unknown>
#2 0x562c46f30ce2 <unknown>
#3 0x562c46f32162 <unknown>
#4 0x562c46f320b4 <unknown>
#5 0x562c46f2258e <unknown>
#6 0x562c46f22245 <unknown>
#7 0x562c46fade2c <unknown>
#8 0x562c46fad47f <unknown>
#9 0x562c46fa4de3 <unknown>
#10 0x562c46f7a2dd <unknown>
#11 0x562c46f7b34e <unknown>
#12 0x562c471da3e4 <unknown>
#13 0x562c471de3d7 <unknown>
#14 0x562c471e8b20 <unknown>
#15 0x562c471df023 <unknown>
#16 0x562c471ad1aa <unknown>
#17 0x562c472036b8 <unknown>
#18 0x562c47203847 <unknown>
#19 0x562c47213243 <unknown>
#20 0x7f49b19111c4 <unknown>

[2025-01-07T01:41:56.067+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-07T01:41:56.085+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T01:41:56.089+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
