[2025-01-07T00:13:42.777+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-07T00:13:42.789+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ico_scraping_dag_latest.scrape_ico_data scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-07T00:13:42.794+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ico_scraping_dag_latest.scrape_ico_data scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-01-07T00:13:42.794+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2025-01-07T00:13:42.804+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_ico_data> on 2025-01-06 00:00:00+00:00
[2025-01-07T00:13:42.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ico_scraping_dag_latest', 'scrape_ico_data', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/selenium_dag_01.py', '--cfg-path', '/tmp/tmprgxxp7q2']
[2025-01-07T00:13:42.814+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask scrape_ico_data
[2025-01-07T00:13:42.815+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=586) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-07T00:13:42.815+0000] {standard_task_runner.py:72} INFO - Started process 588 to run task
[2025-01-07T00:13:42.853+0000] {task_command.py:467} INFO - Running <TaskInstance: ico_scraping_dag_latest.scrape_ico_data scheduled__2025-01-06T00:00:00+00:00 [running]> on host 409c0fd90ee9
[2025-01-07T00:13:42.913+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ico_scraping_dag_latest' AIRFLOW_CTX_TASK_ID='scrape_ico_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-01-07T00:13:42.913+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-07T00:13:42.926+0000] {logging_mixin.py:190} INFO - Starting the web scraping process...
[2025-01-07T00:13:42.977+0000] {logging_mixin.py:190} INFO - Chrome version: Chromium 114.0.5735.0
[2025-01-07T00:13:42.978+0000] {logging_mixin.py:190} INFO - ChromeDriver version: ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})
[2025-01-07T00:13:42.978+0000] {logging_mixin.py:190} INFO - Chrome binary location set to: /opt/chrome/chrome
[2025-01-07T00:13:42.979+0000] {logging_mixin.py:190} INFO - ChromeDriver path set to: /opt/chromedriver/chromedriver
[2025-01-07T00:13:43.487+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 152, in scrape_data
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from no such execution context: uniqueContextId not found
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x5589e22b24e3 <unknown>
#1 0x5589e1fe1c76 <unknown>
#2 0x5589e1fcb8c3 <unknown>
#3 0x5589e1fc9bac <unknown>
#4 0x5589e1fca162 <unknown>
#5 0x5589e1fe5af1 <unknown>
#6 0x5589e1fe797e <unknown>
#7 0x5589e1fe7a4c <unknown>
#8 0x5589e2046f77 <unknown>
#9 0x5589e204547f <unknown>
#10 0x5589e203cde3 <unknown>
#11 0x5589e20122dd <unknown>
#12 0x5589e201334e <unknown>
#13 0x5589e22723e4 <unknown>
#14 0x5589e22763d7 <unknown>
#15 0x5589e2280b20 <unknown>
#16 0x5589e2277023 <unknown>
#17 0x5589e22451aa <unknown>
#18 0x5589e229b6b8 <unknown>
#19 0x5589e229b847 <unknown>
#20 0x5589e22ab243 <unknown>
#21 0x7fd4bbf251c4 <unknown>

[2025-01-07T00:13:43.521+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ico_scraping_dag_latest, task_id=scrape_ico_data, run_id=scheduled__2025-01-06T00:00:00+00:00, execution_date=20250106T000000, start_date=20250107T001342, end_date=20250107T001343
[2025-01-07T00:13:43.542+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-07T00:13:43.543+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 6 for task scrape_ico_data (Message: session not created
from no such execution context: uniqueContextId not found
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x5589e22b24e3 <unknown>
#1 0x5589e1fe1c76 <unknown>
#2 0x5589e1fcb8c3 <unknown>
#3 0x5589e1fc9bac <unknown>
#4 0x5589e1fca162 <unknown>
#5 0x5589e1fe5af1 <unknown>
#6 0x5589e1fe797e <unknown>
#7 0x5589e1fe7a4c <unknown>
#8 0x5589e2046f77 <unknown>
#9 0x5589e204547f <unknown>
#10 0x5589e203cde3 <unknown>
#11 0x5589e20122dd <unknown>
#12 0x5589e201334e <unknown>
#13 0x5589e22723e4 <unknown>
#14 0x5589e22763d7 <unknown>
#15 0x5589e2280b20 <unknown>
#16 0x5589e2277023 <unknown>
#17 0x5589e22451aa <unknown>
#18 0x5589e229b6b8 <unknown>
#19 0x5589e229b847 <unknown>
#20 0x5589e22ab243 <unknown>
#21 0x7fd4bbf251c4 <unknown>
; 588)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/selenium_dag_01.py", line 152, in scrape_data
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from no such execution context: uniqueContextId not found
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x5589e22b24e3 <unknown>
#1 0x5589e1fe1c76 <unknown>
#2 0x5589e1fcb8c3 <unknown>
#3 0x5589e1fc9bac <unknown>
#4 0x5589e1fca162 <unknown>
#5 0x5589e1fe5af1 <unknown>
#6 0x5589e1fe797e <unknown>
#7 0x5589e1fe7a4c <unknown>
#8 0x5589e2046f77 <unknown>
#9 0x5589e204547f <unknown>
#10 0x5589e203cde3 <unknown>
#11 0x5589e20122dd <unknown>
#12 0x5589e201334e <unknown>
#13 0x5589e22723e4 <unknown>
#14 0x5589e22763d7 <unknown>
#15 0x5589e2280b20 <unknown>
#16 0x5589e2277023 <unknown>
#17 0x5589e22451aa <unknown>
#18 0x5589e229b6b8 <unknown>
#19 0x5589e229b847 <unknown>
#20 0x5589e22ab243 <unknown>
#21 0x7fd4bbf251c4 <unknown>

[2025-01-07T00:13:43.592+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-07T00:13:43.615+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T00:13:43.618+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
