[2025-01-07T15:16:31.483+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-07T15:16:31.496+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ico_scraping_dag_entire_once.scrape_ico_data manual__2025-01-07T15:16:30.624329+00:00 [queued]>
[2025-01-07T15:16:31.504+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ico_scraping_dag_entire_once.scrape_ico_data manual__2025-01-07T15:16:30.624329+00:00 [queued]>
[2025-01-07T15:16:31.504+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-07T15:16:31.515+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_ico_data> on 2025-01-07 15:16:30.624329+00:00
[2025-01-07T15:16:31.525+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ico_scraping_dag_entire_once', 'scrape_ico_data', 'manual__2025-01-07T15:16:30.624329+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ico_scraping_dag_entire_once.py', '--cfg-path', '/tmp/tmppx6mqafh']
[2025-01-07T15:16:31.528+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask scrape_ico_data
[2025-01-07T15:16:31.528+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=818) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-07T15:16:31.529+0000] {standard_task_runner.py:72} INFO - Started process 820 to run task
[2025-01-07T15:16:31.574+0000] {task_command.py:467} INFO - Running <TaskInstance: ico_scraping_dag_entire_once.scrape_ico_data manual__2025-01-07T15:16:30.624329+00:00 [running]> on host 64ebca265122
[2025-01-07T15:16:31.652+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ico_scraping_dag_entire_once' AIRFLOW_CTX_TASK_ID='scrape_ico_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-07T15:16:30.624329+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-07T15:16:30.624329+00:00'
[2025-01-07T15:16:31.653+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-07T15:16:31.670+0000] {logging_mixin.py:190} INFO - Starting the web scraping process...
[2025-01-07T15:16:31.740+0000] {logging_mixin.py:190} INFO - Chrome version: Chromium 114.0.5735.0
[2025-01-07T15:16:31.741+0000] {logging_mixin.py:190} INFO - ChromeDriver version: ChromeDriver 114.0.5735.90 (386bc09e8f4f2e025eddae123f36f6263096ae49-refs/branch-heads/5735@{#1052})
[2025-01-07T15:16:31.741+0000] {logging_mixin.py:190} INFO - Chrome binary location set to: /opt/chrome/chrome
[2025-01-07T15:16:31.742+0000] {logging_mixin.py:190} INFO - ChromeDriver path set to: /opt/chromedriver/chromedriver
[2025-01-07T15:16:32.241+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ico_scraping_dag_entire_once.py", line 153, in scrape_data
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from no such execution context: loader has changed while resolving nodes
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x55cce097e4e3 <unknown>
#1 0x55cce06adc76 <unknown>
#2 0x55cce06b14bb <unknown>
#3 0x55cce06b397e <unknown>
#4 0x55cce06b3a4c <unknown>
#5 0x55cce0712f77 <unknown>
#6 0x55cce071147f <unknown>
#7 0x55cce0708de3 <unknown>
#8 0x55cce06de2dd <unknown>
#9 0x55cce06df34e <unknown>
#10 0x55cce093e3e4 <unknown>
#11 0x55cce09423d7 <unknown>
#12 0x55cce094cb20 <unknown>
#13 0x55cce0943023 <unknown>
#14 0x55cce09111aa <unknown>
#15 0x55cce09676b8 <unknown>
#16 0x55cce0967847 <unknown>
#17 0x55cce0977243 <unknown>
#18 0x7f78f6eed1c4 <unknown>

[2025-01-07T15:16:32.256+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ico_scraping_dag_entire_once, task_id=scrape_ico_data, run_id=manual__2025-01-07T15:16:30.624329+00:00, execution_date=20250107T151630, start_date=20250107T151631, end_date=20250107T151632
[2025-01-07T15:16:32.270+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-07T15:16:32.270+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task scrape_ico_data (Message: session not created
from no such execution context: loader has changed while resolving nodes
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x55cce097e4e3 <unknown>
#1 0x55cce06adc76 <unknown>
#2 0x55cce06b14bb <unknown>
#3 0x55cce06b397e <unknown>
#4 0x55cce06b3a4c <unknown>
#5 0x55cce0712f77 <unknown>
#6 0x55cce071147f <unknown>
#7 0x55cce0708de3 <unknown>
#8 0x55cce06de2dd <unknown>
#9 0x55cce06df34e <unknown>
#10 0x55cce093e3e4 <unknown>
#11 0x55cce09423d7 <unknown>
#12 0x55cce094cb20 <unknown>
#13 0x55cce0943023 <unknown>
#14 0x55cce09111aa <unknown>
#15 0x55cce09676b8 <unknown>
#16 0x55cce0967847 <unknown>
#17 0x55cce0977243 <unknown>
#18 0x7f78f6eed1c4 <unknown>
; 820)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ico_scraping_dag_entire_once.py", line 153, in scrape_data
    driver = webdriver.Chrome(service=service, options=chrome_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 241, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 329, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from no such execution context: loader has changed while resolving nodes
  (Session info: chrome=114.0.5735.0)
Stacktrace:
#0 0x55cce097e4e3 <unknown>
#1 0x55cce06adc76 <unknown>
#2 0x55cce06b14bb <unknown>
#3 0x55cce06b397e <unknown>
#4 0x55cce06b3a4c <unknown>
#5 0x55cce0712f77 <unknown>
#6 0x55cce071147f <unknown>
#7 0x55cce0708de3 <unknown>
#8 0x55cce06de2dd <unknown>
#9 0x55cce06df34e <unknown>
#10 0x55cce093e3e4 <unknown>
#11 0x55cce09423d7 <unknown>
#12 0x55cce094cb20 <unknown>
#13 0x55cce0943023 <unknown>
#14 0x55cce09111aa <unknown>
#15 0x55cce09676b8 <unknown>
#16 0x55cce0967847 <unknown>
#17 0x55cce0977243 <unknown>
#18 0x7f78f6eed1c4 <unknown>

[2025-01-07T15:16:32.306+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-07T15:16:32.324+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-07T15:16:32.325+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
